#!/bin/sh

# PROVIDE: bsdrngd
# REQUIRE: devd
# KEYWORD: nojail

. /etc/rc.subr

name=bsdrngd
rcvar=bsdrngd_enable
stop_cmd=bsdrngd_stop
command="/usr/local/sbin/bsdrngd"
command_args="-d"

bsdrngd_stop()
{
	cat /var/run/bsd-rngd.pid | xargs kill -9
	rm /var/run/bsd-rngd.pid
}


load_rc_config $name
run_rc_command "$1" 
