#!/bin/sh

. /etc/rc.subr

name=bsdrngd
rcvar=bsdrngd_enable
start_cmd="${name}_enable"
stop_cmd=":"
command="/usr/local/sbin/${name}"

bsdrngd_enable()
{
	/usr/local/sbin/bsdrngd
}


load_rc_config $name
run_rc_command "$1" 
